CalFoscari/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from front.views import register
from django_otp.admin import OTPAdminSite


admin.site.site_title = "Cal Foscari"
admin.site.site_header = "Ca Foscari Calendar"
admin.site.index_title = "Calendar"
admin.site.__class__ = OTPAdminSite

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/register/', register, name='register'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('', include('front.urls')),
    path('api/', include('coursesCalendars.urls')),
]

coursesCalendars/urls.py
from django.urls import path
from . import views_courses, views_calendars

app_name = 'coursesCalendars'

urlpatterns = [
    path('courses/', views_courses.CoursesList.as_view(), name='courses'),
    path('courses/<int:pk>', views_courses.CoursesDetail.as_view(), name='courses_detail'),
    path('userCourses/', views_courses.UserCoursesList.as_view(), name='userCourses'),
    path('userCourses/<int:pk>', views_courses.UserCoursesDetail.as_view(), name='userCourses_detail'),
    path('courses/<int:pk>/save', views_courses.save_course, name='courses_save'),
    path('courses/<int:pk>/unsave', views_courses.unsave_course, name='courses_unsave'),
    path('calendars/', views_calendars.get_calendar, name='calendars'),
]

front/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('calendar', views.calendar, name='calendar'),
    path('my_courses', views.my_courses, name='my_courses'),
    path('search_courses', views.search_courses, name='search_courses'),
]

front/models.py
from django.db import models

# Create your models here.

front/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Password and confirm_password does not match")

    class Meta:
        model = User
        fields = ('username', 'password')

front/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import UserForm
from django.contrib.auth.password_validation import validate_password


# @login_required
def home(request):
    return render(request, 'front/home.html')


@login_required
def calendar(request):
    return render(request, 'front/calendar.html')


@login_required
def search_courses(request):
    return render(request, 'front/search_courses.html')


@login_required
def my_courses(request):
    return render(request, 'front/my_courses.html')


def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user = user_form.save(commit=False)
        if user_form.is_valid() and validate_password(user.password, user=user) is None:
            user.set_password(user.password)
            user.save()
            return redirect('home')
        else:
            return render(request, 'front/registration.html', {'user_form': user_form})

    else:
        user_form = UserForm()
        return render(request, 'front/registration.html', {'user_form': user_form})

front/templates/front/calendar.html
{% extends "base_generic.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.4.0/main.min.css" integrity="sha256-HDFjvqItXdjW7TEM0cjN/9o9CRPkpo5hmGtd6AqN124=" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.4.0/main.min.js" integrity="sha256-niYpAJmpGSi28F0cwFTEQu2cCnJ9Jf+x2UkTYoXH3rk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.4.0/locales/en-gb.js" integrity="sha256-c5aig17Zw7NJwvtFu60sTHakIH3YnHYaMU6xoKDz12c=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.4.0/main.min.css" integrity="sha256-Nt1jjcb7BjpIGL9BEJjnZN9sySJXdYIvyBhMoao3fug=" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.4.0/main.min.js" integrity="sha256-Ci3guQkgtPJpRMjkJCPy1Pg2DnU/8ZFQ+D0HxLaNO1o=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.4.0/main.min.css" integrity="sha256-WID6AXzUvFn5HbDibqulC5qT6/BEVF06KgFUYTFYDUM=" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.4.0/main.min.js" integrity="sha256-D4OwfygAhZJBz54RrbJ3tYzO2yNC+cySO56cCvdfxaA=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/calendar.css' %}" />

    <style>
    .fc-event-container
    {
        {#font-weight: bold;#}
    }
    </style>
{% endblock %}

{% block content %}
{% url "coursesCalendars:calendars" as api_calendars %}

<h1>Calendar</h1>

<div id="calendarContainer" class="col row">
    <div id='calendar'></div>
</div>

<script>
    let calendar;
    document.addEventListener('DOMContentLoaded', function() {
        let calendarEl = document.getElementById('calendar');

        calendarConfig =
        {
            plugins: [ 'dayGrid', 'timeGrid' ],
            height: 'auto',
            minTime: '08:00:00',
            maxTime: '21:00:00',
            firstDay: 1, //Monday = 1
            weekends: false,
            allDaySlot: false,
            nowIndicator: true,
            slotEventOverlap: false,
            events: getEvents,
            titleFormat:
            {
                month: 'long',
                year: 'numeric',
                day: 'numeric',
            },
            //slotDuration: '00:15:00',
            slotDuration: '00:30:00',
            slotLabelInterval: '01:00:00',
            slotLabelFormat:
            {
                hour: 'numeric',
                hour12: false,
                minute: '2-digit',
                omitZeroMinute: false,
                meridiem: false
            },
            eventTimeFormat:
            {
                hour: 'numeric',
                hour12: false,
                minute: '2-digit',
                omitZeroMinute: false,
                meridiem: false
            },
        };

        if($(window).width() < 770)
        {
            calendarConfig.defaultView = 'timeGridDay';
            calendarConfig.columnHeaderFormat = {
                weekday: 'long',
                day: 'numeric',
                month: 'long',
            };
            calendarConfig.header = {
                left:   '',
                center: '',
                right:  'today prev,next'
            };
        }
        else
        {
            calendarConfig.defaultView = 'timeGridWeek';
            calendarConfig.columnHeaderFormat=
            {
                //weekday: 'long',
                //day: '2-digit',
                day: 'numeric',
                omitCommas: true
            };
        }

        calendar = new FullCalendar.Calendar(calendarEl, calendarConfig);

        function getTextColor(rgb)
        {
            // https://www.w3.org/TR/AERT/#color-contrast
            rgb = rgb.split('');
            let r = parseInt(rgb[1] + rgb[2], 16)
            let g = parseInt(rgb[3] + rgb[4], 16)
            let b = parseInt(rgb[5] + rgb[6], 16)
            let brightness = ((r * 299) + (g * 587) + (b * 114)) / 1000;
            return (brightness > 127) ? '#000000' : '#ffffff';
        }

        function getLocalDate(value)
        {
            return new Date(value.getTime() - (value.getTimezoneOffset() * 60000)).toISOString().split('T')[0];
        }

        function getEvents(info, successCallback, failureCallback)
        {
            console.log(info.start);
            console.log(info.start.toISOString());
            console.log(info.start.toISOString().split('T')[0]);
            console.log(info.end);
            console.log(info.end.toISOString());
            console.log(info.end.toISOString().split('T')[0]);
            let request =
            {
                url : '{{ api_calendars }}?from=' + getLocalDate(info.start) + '&to=' + getLocalDate(info.end),
                dataType : 'json',
                success: function (response, state)
                {
                    let output = [];
                    for(let l in response['lessons'])
                    {
                        let lesson = response['lessons'][l];
                        let course = response['courses'][lesson['ar_id']];
                        output.push(
                            {
                                title: course['name'],
                                start: lesson['begin_datetime'],
                                end: lesson['end_datetime'],
                                color: course['custom_color'],
                                textColor: getTextColor(course['custom_color']),
                            });
                    }

                    successCallback(output);
                },
                error: failureCallback,
            };
            jQuery.ajax(request).then(function()
            {
                calendar.render();
            });
        }

        calendar.render();
    });
</script>
{% endblock %}

front/templates/front/home.html
{% extends "base_generic.html" %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
<h1>Home</h1>
{% endblock %}

front/templates/front/my_courses.html
{% extends "base_generic.html" %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
    {% url "coursesCalendars:courses" as api_courses %}
    {% url "search_courses" as search_courses %}

    <div class="row">
        <div class="col-auto">
            <h4>My Courses</h4>
        </div>
        <div class="col-auto">
            <a class="btn btn-success" href="{{ search_courses }}"><i class="fas fa-plus"></i></a>
        </div>
    </div>
    <div class="row">
        <div class="col-xl">
            <table id="courses_table" class="align-center table table-striped" style="margin-top: 15px">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col" class="text-center">Year</th>
                    <th scope="col">Partition</th>
                    <th scope="col">Color</th>
                    <th scope="col" class="text-center">Remove Course</th>
                  </tr>
                </thead>
                <tbody>
                </tbody>
              </table>

        </div>
    </div>

<script>
'use strict';

let coursesTableBody = $('#courses_table tbody');

function getData()
{
    let request =
    {
        url : '{{ api_courses }}?myCourses=true',
        dataType : 'json',
        success: function (response, state)
        {
            redrawTable(response);
        }
    };

    jQuery.ajax(request);
    return false;
}

function redrawTable(results)
{
    let newHtml = '';
    for(let i in results)
    {
        newHtml += '<tr id="' + results[i].af_id + '">';
        newHtml +=      '<th scope="row">' + results[i].code + '</th>';
        newHtml +=      '<td>' + results[i].name + '</td>';
        newHtml +=      '<td class="text-center">' + results[i].year + '</td>';
        newHtml +=      '<td>' + results[i].partition + '</td>';
        newHtml +=      '<td>' + 'Color' + '</td>';
        newHtml +=      '<td class="text-center"><button class="btn btn-sm btn-danger" type="button" onclick="unsaveCourse(this);">';
            newHtml +=      '<i class="fas fa-trash-alt"></i>';
        newHtml +=      '</button></td>';
        newHtml += '</tr>';
    }
    coursesTableBody.html(newHtml);
}

function unsaveCourse(sender)
{
    let $row = $(sender).parent().parent();
    let courseId = $row.attr('id');
    let request =
        {
            url : '{{ api_courses }}' + courseId + '/unsave',
            success: function ()
            {
                $row.remove();
            }
        };
    jQuery.ajax(request);
}

getData();
</script>


{% endblock %}

front/templates/front/registration.html
{% extends "base_generic.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}

{% block navbar %}{% endblock %}

{% block content %}
    <form action="{{ app_path }}" method="post" id="login-form" class="form-registration text-center">
        {% csrf_token %}
        <a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" class="img-fluid" alt="logo"/></a>
        <h4 class="mb-3 mt-3 ml-1 font-weight-normal" style="text-align: center;">Register</h4>
        {{ user_form.username.errors }}
        <input type="text" name="username" autofocus="" maxlength="150" required="" id="id_username" class="form-control" placeholder="Username">
        {{ user_form.password.errors }}
        <input type="password" name="password" required="" id="id_password" class="form-control" placeholder="Password">
        <input type="password" name="confirm_password" required="" id="id_confirm_password" class="form-control" placeholder="Confirm Password">
        <button type="submit" class="btn btn-block btn-lg btn-danger bg-foscari">Login</button>
    </form>
{% endblock %}

front/templates/front/searchCourses.html
{% extends "base_generic.html" %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
    {% url "coursesCalendars:courses" as api_courses %}

    <h4>Search Courses</h4>
    <div class="row">
        <div class="col-xl">
            <form class="" onsubmit="performSearch(event);">
                <input id="search_text" name="search" type="text" required="" autofocus="" class="form-control" placeholder="Search" style="margin-bottom: 5px;" />
                <select id="search_year" class="form-control" style="margin-bottom: 5px; max-width: max-content;">
                    <option value="">All Years</option>
                    <option value="0">No Year Defined</option>
                    <option value="1">Year 1</option>
                    <option value="2">Year 2</option>
                    <option value="3">Year 3</option>
                </select>
                <input id="search_send" type="submit" value="Search" class="btn btn-primary" />
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-xl">
            <table id="courses_table" class="align-center table table-striped" style="margin-top: 15px">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col" class="text-center">Year</th>
                    <th scope="col">Partition</th>
                    <th scope="col" class="text-center">Save Course</th>
                  </tr>
                </thead>
                <tbody>
                </tbody>
              </table>

        </div>
    </div>

<script>
'use strict';

let searchText = $('#search_text');
let searchYear = $('#search_year');
let coursesTableBody = $('#courses_table tbody');

function performSearch(e)
{
    e.preventDefault();
    let request =
    {
        url : '{{ api_courses }}?search=' + searchText.val() + '&year=' + searchYear.val(),
        dataType : 'json',
        success: function (response, state)
        {
            console.log(response);
            redrawTable(response);
        }
    };

    clearTable();
    jQuery.ajax(request);
    return false;
}

function clearTable()
{
    coursesTableBody.html('');
}

function redrawTable(results)
{
    let newHtml = '';
    for(let i in results)
    {
        newHtml += '<tr id="' + results[i].af_id + '">';
        newHtml +=     '<th scope="row">' + results[i].code + '</th>';
        newHtml +=     '<td>' + results[i].name + '</td>';
        newHtml +=     '<td class="text-center">' + results[i].year + '</td>';
        newHtml +=     '<td>' + results[i].partition + '</td>';
        newHtml +=     '<td class="text-center"><button class="btn btn-sm btn-success" type="button"><i class="far fa-bookmark"></i></button></td>';
        newHtml += '</tr>';
    }
    coursesTableBody.html(newHtml);
}
</script>


{% endblock %}

front/templates/front/search_courses.html
{% extends "base_generic.html" %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
    {% url "coursesCalendars:courses" as api_courses %}

    <h4>Search Courses</h4>
    <div class="row">
        <div class="col-xl">
            <form class="" onsubmit="performSearch(event);">
                <input id="search_text" name="search" type="text" required="" autofocus="" class="form-control" placeholder="Search" style="margin-bottom: 5px;" />
                <select id="search_year" class="form-control" style="margin-bottom: 5px; max-width: max-content;">
                    <option value="">All Years</option>
                    <option value="0">No Year Defined</option>
                    <option value="1">Year 1</option>
                    <option value="2">Year 2</option>
                    <option value="3">Year 3</option>
                </select>
                <input id="search_send" type="submit" value="Search" class="btn btn-danger bg-foscari" />
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-xl">
            <table id="courses_table" class="align-center table table-striped" style="margin-top: 15px">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col" class="text-center">Year</th>
                    <th scope="col">Partition</th>
                    <th scope="col" class="text-center">Save Course</th>
                  </tr>
                </thead>
                <tbody>
                </tbody>
              </table>

        </div>
    </div>

<script>
'use strict';

let searchText = $('#search_text');
let searchYear = $('#search_year');
let coursesTableBody = $('#courses_table tbody');

function performSearch(e)
{
    e.preventDefault();
    let request =
    {
        url : '{{ api_courses }}?search=' + searchText.val() + '&year=' + searchYear.val(),
        dataType : 'json',
        success: function (response, state)
        {
            {#console.log(response);#}
            redrawTable(response);
        }
    };

    clearTable();
    jQuery.ajax(request);
    return false;
}

function clearTable()
{
    coursesTableBody.html('');
}

function redrawTable(results)
{
    let newHtml = '';
    for(let i in results)
    {
        newHtml += '<tr id="' + results[i].af_id + '">';
        newHtml +=      '<th scope="row">' + results[i].code + '</th>';
        newHtml +=      '<td>' + results[i].name + '</td>';
        newHtml +=      '<td class="text-center">' + results[i].year + '</td>';
        newHtml +=      '<td>' + results[i].partition + '</td>';
        newHtml +=      '<td class="text-center"><button class="btn btn-sm btn-success" type="button" onclick="saveCourse(this);" data-saved="' + results[i].saved + '">';
        if(results[i].saved)
            newHtml +=      '<i class="fas fa-bookmark"></i>';
        else
            newHtml +=      '<i class="far fa-bookmark"></i>';
        newHtml +=      '</button></td>';
        newHtml += '</tr>';
    }
    coursesTableBody.html(newHtml);
}

function saveCourse(sender)
{
    let $button = $(sender);
    let courseId = $button.parent().parent().attr('id');
    let saved = $button.data("saved");
    let request;
    if(saved)
        request =
        {
            url : '{{ api_courses }}' + courseId + '/unsave',
            success: function ()
            {
                $button.html('<i class="far fa-bookmark"></i>');
                $button.data('saved', false);
            }
        };
    else
        request =
        {
            url : '{{ api_courses }}' + courseId + '/save',
            success: function ()
            {
                $button.html('<i class="fas fa-bookmark"></i>');
                $button.data('saved', true);
            }
        };
    jQuery.ajax(request);
}
</script>


{% endblock %}